name: Release

on: [push]
jobs:
  setup_env:
    name: build and publish
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    permissions: write-all
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
        with:
          repository: "SagerNet/sing-box-for-android"
          path: "sing-box-for-android"
          fetch-depth: "0"

      - uses: actions/checkout@v4
        with:
          path: "sb"

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Android SDK
        uses: amyu/setup-android@v2
        with:
          ndk-version: "23.1.7779620"

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.1

      - uses: goreleaser/goreleaser-action@v4
        with:
          install-only: true
      - run: go install -v github.com/tcnksm/ghr@latest

      - run: |
          cd ./sb
          make lib_install
          make release_android
          make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
